/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 05 19:22:19 GMT 2017
 */

package org.araguacaima.utils;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS = true,
                     useVNET = true,
                     resetStaticState = true,
                     separateClassLoader = true,
                     useJEE = true)
public class ZipUtils_ESTest extends ZipUtils_ESTest_scaffolding {
    @Test
    public void notGeneratedAnyTest() {
        // EvoSuite did not generate any tests
    }
}
