/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 06 20:11:09 GMT 2017
 */

package org.araguacaima.commons.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import org.araguacaima.commons.utils.JarUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JarUtils_ESTest extends JarUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      ArrayList<String> arrayList0 = jarUtils0.listClassesOnJar("Yk |c");
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      boolean boolean0 = jarUtils0.findClassOnJar("2Bk", "s+$P$hx!2Q7cJ'q");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      // Undeclared exception!
      try { 
        jarUtils0.generateJarFromDirectory((String) null, (String) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:\\Workspace\\araguacaima\\commons-utils\\2Bk");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      try { 
        jarUtils0.generateJarFromDirectory("{Tk]s9ud3;$L5z", "2Bk", 1);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      try { 
        jarUtils0.generateJarFromDirectory("2+)R)@9ps6;G<|Yr;", "", 676);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      // Undeclared exception!
      try { 
        jarUtils0.generateJarFromDirectory((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      FileSystemHandling.shouldAllThrowIOExceptions();
      try { 
        jarUtils0.generateJarFromDirectory("65TDhu", "M+= Bq@c:$");
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JarUtils jarUtils0 = new JarUtils();
      try { 
        jarUtils0.generateJarFromDirectory("", "");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

}
