/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 05 19:28:25 GMT 2017
 */

package org.araguacaima.commons.utils;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS = true,
                     useVNET = true,
                     resetStaticState = true,
                     separateClassLoader = true,
                     useJEE = true)
public class UnicodeUtils_ESTest extends UnicodeUtils_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0()
            throws Throwable {
        UnicodeUtils unicodeUtils0 = new UnicodeUtils();
        assertEquals('\u00BF', UnicodeUtils.INTERROGACION_ABRE);
    }
}
