/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 06 20:18:47 GMT 2017
 */

package org.araguacaima.commons.exception.core;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Date;
import org.araguacaima.commons.exception.core.ApplicationGeneralExceptionImpl;
import org.araguacaima.commons.exception.core.EnvironmentThrowableInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ApplicationGeneralException_ESTest extends ApplicationGeneralException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ApplicationGeneralExceptionImpl applicationGeneralExceptionImpl0 = new ApplicationGeneralExceptionImpl("");
      applicationGeneralExceptionImpl0.environmentThrowableInfo = null;
      EnvironmentThrowableInfo environmentThrowableInfo0 = applicationGeneralExceptionImpl0.getEnvironmentThrowableInfo();
      assertNull(environmentThrowableInfo0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ApplicationGeneralExceptionImpl applicationGeneralExceptionImpl0 = new ApplicationGeneralExceptionImpl("");
      ApplicationGeneralExceptionImpl applicationGeneralExceptionImpl1 = new ApplicationGeneralExceptionImpl("PRINT_STACK_TRACE", applicationGeneralExceptionImpl0);
      assertNull(applicationGeneralExceptionImpl1.getMessage());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ApplicationGeneralExceptionImpl applicationGeneralExceptionImpl0 = new ApplicationGeneralExceptionImpl("");
      EnvironmentThrowableInfo environmentThrowableInfo0 = applicationGeneralExceptionImpl0.getEnvironmentThrowableInfo();
      assertNotNull(environmentThrowableInfo0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ApplicationGeneralExceptionImpl applicationGeneralExceptionImpl0 = new ApplicationGeneralExceptionImpl((String) null);
      Date date0 = applicationGeneralExceptionImpl0.getOccurrenceDateAndTime();
      assertNull(date0);
  }
}
