/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 06 20:16:51 GMT 2017
 */

package org.araguacaima.commons.exception.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.MockitoExtension.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Locale;
import org.araguacaima.commons.exception.core.Exceptions;
import org.araguacaima.commons.exception.core.TechnicalException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Exceptions_ESTest extends Exceptions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Exceptions.setBundleName((String) null);
      String string0 = Exceptions.getBundleName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = Exceptions.getBundleName();
      assertEquals("exceptions.properties", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = Exceptions.getMessage("BD0005");
      assertEquals("[[BD0005]]", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Exceptions exceptions0 = new Exceptions();
      assertEquals("exceptions.properties", exceptions0.getBundleName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Exceptions.setBundleName("");
      String string0 = Exceptions.getBundleName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Locale locale0 = new Locale("", "]3?#,- 8o:MNA<xP");
      String string0 = Exceptions.getMessage("Error adding data from file '", locale0);
      assertEquals("[[Error adding data from file ']]", string0);
  }

}
