/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 08 16:32:28 GMT 2017
 */

package com.araguacaima.commons.exception.core;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS = true,
                     useVNET = true,
                     resetStaticState = true,
                     separateClassLoader = true,
                     useJEE = true)
public class PropertiesUtilException_ESTest extends PropertiesUtilException_ESTest_scaffolding {

    @Test
    public void test0()
            throws Throwable {
        PropertiesUtilException propertiesUtilException0 = new PropertiesUtilException("");
    }
}
