/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 08 16:29:59 GMT 2017
 */

package com.araguacaima.commons.exception.core;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Collection;

import static org.junit.Assert.assertNotNull;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS = true,
                     useVNET = true,
                     resetStaticState = true,
                     separateClassLoader = true,
                     useJEE = true)
public class ThrowableStackTraceRenderer_ESTest extends ThrowableStackTraceRenderer_ESTest_scaffolding {

    @Test
    public void test0()
            throws Throwable {
        MockThrowable mockThrowable0 = new MockThrowable();
        mockThrowable0.setOriginForDelegate((StackTraceElement) null);
        Collection collection0 = ThrowableStackTraceRenderer.render(mockThrowable0);
        assertNotNull(collection0);
    }

    @Test
    public void test1()
            throws Throwable {
        MockThrowable mockThrowable0 = new MockThrowable();
        Collection collection0 = ThrowableStackTraceRenderer.render(mockThrowable0);
        assertNotNull(collection0);
    }

    @Test
    public void test2()
            throws Throwable {
        ThrowableStackTraceRenderer throwableStackTraceRenderer0 = new ThrowableStackTraceRenderer();
    }
}
