/*
 * This file was automatically generated by EvoSuite
 * Fri Sep 08 16:31:53 GMT 2017
 */

package com.araguacaima.commons.exception.aop;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertNull;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS = true,
                     useVNET = true,
                     resetStaticState = true,
                     separateClassLoader = true,
                     useJEE = true)
public class ExceptionsAspect_ESTest extends ExceptionsAspect_ESTest_scaffolding {

    @Test
    public void test0()
            throws Throwable {
        ExceptionsAspect exceptionsAspect0 = new ExceptionsAspect();
        MockThrowable mockThrowable0 = new MockThrowable();
        exceptionsAspect0.errorInterceptor(mockThrowable0);
        assertNull(mockThrowable0.getMessage());
    }
}
